"""
The open-source backend — compile the SAME MapSpec into a GeoPandas /
matplotlib script instead of arcpy.

    map2arcpy generate <input> --target geopandas -o map.py

No Esri license needed to RUN the output: the generated script uses
geopandas + matplotlib (pip-installable anywhere), with mapclassify for
class breaks, and optional contextily (web basemaps) / rasterio (rasters)
degrading gracefully to a note when absent.

Same contract as the arcpy backend: deterministic, single-file, CONFIG dict
on top, missing-input audit before any work, every unresolved thing an
explicit TODO, `ast.parse`-verified before it is handed over. Where the two
backends genuinely differ (no layouts/basemap service, SQL where-clauses vs
pandas queries), the difference is stated in the script, not papered over.
"""
from __future__ import annotations

import ast
import datetime
import re
from typing import Any, Dict, List, Optional

from ..spec import MapSpec, Layer, Operation

GENERATOR_NAME = "map2arcpy"

#: MapSpec ramp names -> matplotlib colormap names
_CMAPS = {
    "greens": "Greens", "blues": "Blues", "reds": "Reds", "oranges": "Oranges",
    "purples": "Purples", "greys": "Greys", "viridis": "viridis",
    "magma": "magma", "plasma": "plasma", "cividis": "cividis",
    "red_blue": "RdBu", "brown_teal": "BrBG", "red_yellow_green": "RdYlGn",
    "spectral": "Spectral", "pink_green": "PiYG",
}

_PAGES = {  # inches, landscape/portrait honoured
    "A4P": (8.27, 11.69), "A4L": (11.69, 8.27),
    "A3P": (11.69, 16.54), "A3L": (16.54, 11.69),
    "LetterP": (8.5, 11.0), "LetterL": (11.0, 8.5),
}

_CLASSIFY = {"natural_breaks": "NaturalBreaks", "quantile": "Quantiles",
             "equal_interval": "EqualInterval", "geometric": "StdMean",
             "std_dev": "StdMean"}


def generate_gpd(spec: MapSpec, strict: bool = True,
                 profile: Optional[Dict[str, Any]] = None) -> str:
    """Compile a MapSpec into GeoPandas/matplotlib script text. The `profile`
    argument (an ArcGIS Pro probe profile) is accepted for interface parity
    and ignored — this backend has no Esri dependency to adapt to."""
    errors = spec.validate()
    if errors and strict:
        raise ValueError("MapSpec invalid:\n  - " + "\n  - ".join(errors))

    parts = [
        _header(spec, errors),
        _config(spec),
        _RUNTIME,
        _main(spec),
    ]
    code = "\n".join(parts)
    try:
        ast.parse(code)
    except SyntaxError as e:  # pragma: no cover — generator bug guard
        raise RuntimeError(f"internal error: generated script does not parse: {e}") from e
    return code


# ---------------------------------------------------------------------------
def _safe(s: str) -> str:
    s = " ".join(str(s).split())
    return s.replace('"""', "'''").replace("\\", "/")


def _ident(name: str) -> str:
    return re.sub(r"\W+", "_", str(name)).strip("_") or "layer"


def _header(spec: MapSpec, errors: List[str]) -> str:
    today = datetime.date.today().isoformat()
    title = _safe(spec.layout.title)
    lines = [
        "#!/usr/bin/env python",
        "# -*- coding: utf-8 -*-",
        '"""',
        title,
        "-" * max(8, len(title)),
        f"Generated by {GENERATOR_NAME} on {today} from a "
        f"'{spec.source_kind}' input — OPEN-SOURCE backend (no ArcGIS needed).",
        "",
        "How to run:",
        "  pip install geopandas matplotlib mapclassify   # once",
        "  python this_file.py",
        "",
        "Optional extras: contextily (web basemaps), rasterio (raster layers).",
        "Edit the CONFIG block below — paths, EPSG, colours — then run.",
        '"""',
    ]
    for n in spec.notes:
        if "NOT UNDERSTOOD" in n:
            lines.append(f"# TODO (step): {_safe(n)}")
        else:
            lines.append(f"# NOTE: {_safe(n)}")
    for e in errors:
        lines.append(f"# TODO (spec issue): {_safe(e)}")
    return "\n".join(lines)


def _config(spec: MapSpec) -> str:
    lay = spec.layout
    lines = ["", "", "# " + "=" * 74,
             "# CONFIG — everything you might need to change",
             "# " + "=" * 74, "CONFIG = {"]
    lines.append(f"    'epsg': {spec.crs_epsg!r},")
    lines.append(f"    'title': {lay.title!r},")
    lines.append(f"    'subtitle': {lay.subtitle!r},")
    credits = lay.credits or f"Generated with {GENERATOR_NAME} | EPSG:{spec.crs_epsg}"
    lines.append(f"    'credits': {credits!r},")
    lines.append(f"    'figsize': {_PAGES.get(lay.page, _PAGES['A4P'])!r},  # inches ({lay.page})")
    lines.append(f"    'dpi': {lay.dpi!r},")
    lines.append(f"    'legend': {lay.legend!r}, 'north_arrow': {lay.north_arrow!r}, "
                 f"'scale_bar': {lay.scale_bar!r},")
    export = lay.export
    lines.append(f"    'export': {export!r},")
    op_outputs = {op.output for op in spec.operations if op.output}
    lines.append("    'sources': {")
    for l in spec.layers:
        if l.kind == "basemap" or l.name in op_outputs:
            continue                            # op outputs are computed, not loaded
        src = l.source or "TODO_SET_PATH"
        lines.append(f"        {l.name!r}: {src!r},")
    lines.append("    },")
    bm = next((l for l in spec.layers if l.kind == "basemap"), None)
    lines.append(f"    'basemap': {bool(bm)!r},  # needs 'pip install contextily' + internet")
    lines.append("}")
    return "\n".join(lines)


_RUNTIME = '''

# ==========================================================================
# RUNTIME (inlined by map2arcpy — edit CONFIG, not this)
# ==========================================================================
import glob
import os
import sys


def log(msg, level="INFO"):
    print("[%s] %s" % (level, msg))


def audit_inputs(sources):
    """Fail loudly and completely BEFORE any work: list every missing path."""
    missing = [f"  {name}: {path}" for name, path in sources.items()
               if path and path != "TODO_SET_PATH" and not os.path.exists(path)]
    todo = [name for name, path in sources.items() if path == "TODO_SET_PATH"]
    if todo:
        missing.append("  (set CONFIG['sources'] paths for: " + ", ".join(todo) + ")")
    if missing:
        raise SystemExit("missing inputs:\\n" + "\\n".join(missing))


def load_vector(path):
    import geopandas as gpd
    import pandas as pd
    if path.lower().endswith(".csv"):
        df = pd.read_csv(path)
        xcol = next((c for c in df.columns if c.lower() in
                     ("x", "lon", "longitude", "lng")), None)
        ycol = next((c for c in df.columns if c.lower() in
                     ("y", "lat", "latitude")), None)
        if not (xcol and ycol):
            raise SystemExit(f"{path}: no x/y (lon/lat) columns found")
        return gpd.GeoDataFrame(
            df, geometry=gpd.points_from_xy(df[xcol], df[ycol]), crs="EPSG:4326")
    g = gpd.read_file(path)
    if g.crs is None:
        log(f"{path} has no CRS — assuming EPSG:4326; fix in the data if wrong",
            "WARN")
        g = g.set_crs("EPSG:4326")
    return g


def metric(g):
    """A metre-based CRS view for buffers/measurement (UTM auto-estimated)."""
    if g.crs and g.crs.is_geographic:
        return g.to_crs(g.estimate_utm_crs())
    return g


def parse_distance_m(dist):
    """'500 Meters' / '1 Kilometers' / '2 Miles' / '300 Feet' -> metres."""
    val, unit = str(dist).split(None, 1)
    factor = {"meters": 1.0, "kilometers": 1000.0,
              "miles": 1609.344, "feet": 0.3048}[unit.strip().lower()]
    return float(val) * factor


def sql_where(g, clause):
    """Best-effort SQL-where -> pandas query. Differences are real:
    complex SQL should be re-expressed as a pandas query by hand."""
    q = clause
    q = re.sub(r"(?<![<>!=])=(?!=)", "==", q)
    q = re.sub(r"\\bAND\\b", "and", q, flags=re.I)
    q = re.sub(r"\\bOR\\b", "or", q, flags=re.I)
    q = q.replace('"', "")
    try:
        out = g.query(q)
        log(f"select where {clause!r} -> {len(out)} of {len(g)} features")
        return out
    except Exception as e:                     # noqa: BLE001
        log(f"could not translate SQL where {clause!r} ({e}) — "
            "TODO: re-express as a pandas .query()", "WARN")
        return g


def add_basemap(ax, crs):
    try:
        import contextily as cx
        cx.add_basemap(ax, crs=crs)
        log("basemap added (contextily)")
    except ImportError:
        log("basemap requested but contextily is not installed — "
            "'pip install contextily' (needs internet at run time)", "WARN")
    except Exception as e:                     # noqa: BLE001
        log(f"basemap failed ({e}) — continuing without", "WARN")


def north_arrow(ax):
    ax.annotate("N", xy=(0.97, 0.98), xytext=(0.97, 0.90),
                xycoords="axes fraction", ha="center", fontsize=12,
                fontweight="bold",
                arrowprops=dict(arrowstyle="-|>", color="black"))


def scale_bar(ax, g):
    """A simple, honest scale bar from the metric extent."""
    try:
        gm = metric(g)
        xmin, ymin, xmax, ymax = gm.total_bounds
        span = (xmax - xmin) / 4.0
        mag = 10 ** int(len(str(int(span))) - 1)
        nice = max(1, round(span / mag)) * mag
        label = f"{nice/1000:g} km" if nice >= 1000 else f"{nice:g} m"
        frac = nice / (xmax - xmin)
        x0, y0 = 0.05, 0.03
        ax.plot([x0, x0 + frac], [y0, y0], transform=ax.transAxes,
                color="black", linewidth=3)
        ax.text(x0 + frac / 2, y0 + 0.012, label, transform=ax.transAxes,
                ha="center", fontsize=8)
    except Exception as e:                     # noqa: BLE001
        log(f"scale bar skipped ({e})", "WARN")


import re  # noqa: E402  (used by sql_where)
'''


def _op_src(i: str) -> str:
    """An op input: a known layer/op-output name, or a literal path."""
    if any(c in str(i) for c in "/\\") or re.search(
            r"\.(shp|geojson|json|gpkg|kml|csv|gpx)$", str(i), re.I):
        return f"load_vector({i!r})"
    return f"layers[{i!r}]"


def _emit_op(op: Operation) -> List[str]:
    out = _ident(op.output or f"{op.tool}_out")
    ins = [_op_src(i) for i in op.inputs]
    p = op.params
    lines = []
    if p.get("step"):
        lines.append(f"    # ==== {_safe(p['step'])} " + "=" * 10)
    lines.append(f"    # -- {op.tool} -> {out}")
    if op.tool == "buffer":
        dist = p.get("distance", "500 Meters")
        diss = p.get("dissolve", "NONE") == "ALL"
        lines.append(f"    _m = metric({ins[0]})")
        lines.append(f"    _b = _m.buffer(parse_distance_m({dist!r}))")
        if diss:
            lines.append("    _b = gpd.GeoSeries([_b.union_all()], crs=_m.crs)")
        lines.append(f"    {out} = gpd.GeoDataFrame(geometry=_b, crs=_m.crs)"
                     f".to_crs({ins[0]}.crs)")
    elif op.tool == "clip":
        lines.append(f"    {out} = gpd.clip({ins[0]}, "
                     f"{ins[1]}.to_crs({ins[0]}.crs))")
    elif op.tool == "erase":
        lines.append(f"    {out} = gpd.overlay({ins[0]}, "
                     f"{ins[1]}.to_crs({ins[0]}.crs), how='difference')")
    elif op.tool == "dissolve":
        fld = p.get("field")
        lines.append(f"    {out} = {ins[0]}.dissolve(by={fld!r})"
                     + (".reset_index()" if fld else ""))
    elif op.tool == "intersect":
        lines.append(f"    {out} = gpd.overlay({ins[0]}, "
                     f"{ins[1]}.to_crs({ins[0]}.crs), how='intersection')")
    elif op.tool == "union":
        lines.append(f"    {out} = gpd.overlay({ins[0]}, "
                     f"{ins[1]}.to_crs({ins[0]}.crs), how='union')")
    elif op.tool == "merge":
        srcs = ", ".join(f"{i}.to_crs({ins[0]}.crs)" for i in ins)
        lines.append(f"    {out} = gpd.GeoDataFrame(pd.concat([{srcs}], "
                     f"ignore_index=True), crs={ins[0]}.crs)")
    elif op.tool == "spatial_join":
        lines.append(f"    {out} = gpd.sjoin({ins[0]}, "
                     f"{ins[1]}.to_crs({ins[0]}.crs), how='left', "
                     "predicate='intersects')")
    elif op.tool == "select":
        lines.append(f"    {out} = sql_where({ins[0]}, {p.get('where', '1=1')!r})")
    elif op.tool == "near":
        lines.append(f"    {out} = gpd.sjoin_nearest(metric({ins[0]}), "
                     f"metric({ins[1]}), distance_col='NEAR_DIST')")
    elif op.tool == "project":
        epsg = p.get("epsg", 4326)
        lines.append(f"    {out} = {ins[0]}.to_crs(epsg={int(epsg)})")
    elif op.tool == "cell_statistics":
        stat = p.get("stat", "MEAN")
        np_fn = {"MEAN": "nanmean", "SUM": "nansum", "MAXIMUM": "nanmax",
                 "MINIMUM": "nanmin"}.get(stat, "nanmean")
        if p.get("pattern"):
            lines.append(f"    _paths = sorted(glob.glob({p['pattern']!r}))")
        else:
            names = [i for i in op.inputs]
            lines.append(f"    _paths = [CONFIG['sources'][n] for n in {names!r} "
                         "if n in CONFIG['sources']]")
        lines.append("    if not _paths:")
        lines.append(f"        raise SystemExit('cell_statistics: no rasters matched')")
        lines.append("    try:")
        lines.append("        import numpy as np")
        lines.append("        import rasterio")
        lines.append("    except ImportError:")
        lines.append("        raise SystemExit('raster averaging needs rasterio: "
                     "pip install rasterio')")
        lines.append("    with rasterio.open(_paths[0]) as _r0:")
        lines.append("        _prof = _r0.profile")
        lines.append("    _stack = []")
        lines.append("    for _p in _paths:")
        lines.append("        with rasterio.open(_p) as _r:")
        lines.append("            _a = _r.read(1).astype('float64')")
        lines.append("            if _r.nodata is not None:")
        lines.append("                _a[_a == _r.nodata] = float('nan')")
        lines.append("            _stack.append(_a)")
        lines.append(f"    _resarr = np.{np_fn}(np.stack(_stack), axis=0)")
        lines.append(f"    _outpath = os.path.abspath({op.output!r} + '.tif')")
        lines.append("    _prof.update(dtype='float64', count=1, nodata=float('nan'))")
        lines.append("    with rasterio.open(_outpath, 'w', **_prof) as _w:")
        lines.append("        _w.write(_resarr, 1)")
        lines.append(f"    CONFIG['sources'][{op.output!r}] = _outpath")
        lines.append(f"    {out} = _outpath")
        lines.append(f"    log('cell_statistics {stat} over ' + str(len(_paths)) + "
                     "' rasters -> ' + _outpath)")
        return lines
    elif op.tool in ("slope", "hillshade", "euc_distance", "zonal_stats"):
        lines.append(f"    log(\"'{op.tool}' is not supported in the geopandas "
                     "backend yet — generate with --target arcpy for this "
                     "step\", 'WARN')")
        lines.append(f"    {out} = None")
        return lines
    elif op.tool == "multi_buffer":
        dists = list(p.get("distances", [1, 5, 10]))
        unit = p.get("unit", "Kilometers")
        lines.append(f"    _rings = [metric({ins[0]}).buffer("
                     f"parse_distance_m(f'{{d}} {unit}')).union_all() "
                     f"for d in {dists!r}]")
        lines.append(f"    {out} = gpd.GeoDataFrame("
                     f"{{'distance': {dists!r}}}, geometry=_rings, "
                     f"crs=metric({ins[0]}).crs).to_crs({ins[0]}.crs)")
    else:
        lines.append(f"    # TODO: no geopandas translation for '{op.tool}'")
        lines.append(f"    {out} = {ins[0]}")
    lines.append(f"    layers[{op.output!r}] = {out}")
    lines.append(f"    log('{op.tool} done: ' + str(len({out})) + ' features')")
    return lines


def _emit_plot(l: Layer, spec: MapSpec, op_outputs) -> List[str]:
    r = l.renderer
    name = l.name
    lines = [f"    # -- draw: {name}"]
    gref = f"layers[{name!r}]"
    common = "ax=ax, zorder=z"
    if r.transparency:
        common += f", alpha={round(1 - r.transparency / 100.0, 2)}"
    if r.outline:
        common += f", edgecolor={r.outline!r}"
        if r.outline_width:
            common += f", linewidth={r.outline_width}"
    if l.definition_query:
        lines.append(f"    _g = sql_where({gref}, {l.definition_query!r})")
        gref = "_g"
    if r.type == "graduated" and r.field:
        cmap = _CMAPS.get(r.ramp_name or "", "viridis")
        scheme = _CLASSIFY.get(r.class_method or "natural_breaks", "NaturalBreaks")
        k = r.class_count or 5
        lines.append(f"    if {r.field!r} in {gref}.columns:")
        lines.append("        try:")
        lines.append(f"            {gref}.plot(column={r.field!r}, cmap={cmap!r}, "
                     f"scheme={scheme!r}, k={k}, legend=CONFIG['legend'], {common})")
        lines.append("        except ImportError:")
        lines.append(f"            log('mapclassify not installed — continuous "
                     f"ramp used (pip install mapclassify)', 'WARN')")
        lines.append(f"            {gref}.plot(column={r.field!r}, cmap={cmap!r}, "
                     f"legend=CONFIG['legend'], {common})")
        lines.append("    else:")
        msg = f"field '{r.field}' not in {name} — drawn plain; fix the field name"
        lines.append(f"        log({msg!r}, 'WARN')")
        lines.append(f"        {gref}.plot({common})")
    elif r.type == "unique" and r.field:
        lines.append(f"    if {r.field!r} in {gref}.columns:")
        lines.append(f"        {gref}.plot(column={r.field!r}, categorical=True, "
                     f"legend=CONFIG['legend'], cmap='tab20', {common})")
        lines.append("    else:")
        msg = f"field '{r.field}' not in {name} — drawn plain; fix the field name"
        lines.append(f"        log({msg!r}, 'WARN')")
        lines.append(f"        {gref}.plot({common})")
    elif r.type == "stretch":
        cmap = _CMAPS.get(r.ramp_name or "", "gray")
        lines.append(f"    if {name!r} not in CONFIG['sources']:")
        lines.append(f"        log('raster {name} unavailable (its producing "
                     "step was skipped)', 'WARN')")
        lines.append("    else:")
        lines.append("      try:")
        lines.append("        import rasterio")
        lines.append("        from rasterio.plot import show as rio_show")
        lines.append(f"        with rasterio.open(CONFIG['sources'][{name!r}]) as _r:")
        lines.append(f"            rio_show(_r, ax=ax, cmap={cmap!r}, zorder=z)")
        lines.append("      except ImportError:")
        lines.append(f"        log('raster {name} skipped — pip install rasterio', 'WARN')")
        return lines + [f"    log('drawn: {name}')"]
    else:
        col = r.color or "#4C9AA8"
        lines.append(f"    {gref}.plot(color={col!r}, {common})")
    if l.label_field:
        lines.append(f"    if {l.label_field!r} in {gref}.columns:")
        lines.append(f"        for _, _row in {gref}.iterrows():")
        lines.append("            _pt = _row.geometry.representative_point()")
        lines.append(f"            ax.annotate(str(_row[{l.label_field!r}]), "
                     "(_pt.x, _pt.y), fontsize=7, ha='center')")
    lines.append(f"    log('drawn: {name}')")
    return lines


def _main(spec: MapSpec) -> str:
    op_outputs = {op.output for op in spec.operations if op.output}
    lines = [
        "",
        "",
        "# " + "=" * 74,
        "# MAIN",
        "# " + "=" * 74,
        "def main():",
        "    import geopandas as gpd",
        "    import pandas as pd",
        "    import matplotlib",
        "    matplotlib.use('Agg')            # headless-safe; remove to show a window",
        "    import matplotlib.pyplot as plt",
        "",
        "    audit_inputs(CONFIG['sources'])",
        "    layers = {}",
        "    for name, path in CONFIG['sources'].items():",
        "        if path and not path.lower().endswith((" +
        "'.tif', '.tiff', '.img', '.asc', '.hgt', '.jp2', '.dem', '.nc'" + ")):",
        "            layers[name] = load_vector(path)",
        "            log(f'loaded {name}: {len(layers[name])} features '",
        "                f'({layers[name].crs})')",
    ]
    # make gpd/pd visible to op code below (they run inside main's scope)
    if spec.operations:
        lines.append("")
        lines.append("    # ---- geoprocessing " + "-" * 40)
        for op in spec.operations:
            lines.extend(_emit_op(op))
    lines += [
        "",
        "    # ---- map assembly " + "-" * 41,
        "    fig, ax = plt.subplots(figsize=CONFIG['figsize'])",
        "    z = 1",
    ]
    drawn = set()
    # basemap note handled at the end (contextily draws under vectors via zorder)
    from ..spec import RASTER_OPS
    ordered = [l for l in spec.layers if l.kind != "basemap"]
    declared = {l.name for l in ordered}
    for op in spec.operations:
        if op.output and op.output not in declared:
            if op.tool == "zonal_stats":
                continue
            if op.tool in RASTER_OPS:
                from ..spec import Renderer as _R
                ordered.append(Layer(name=op.output, source="", kind="raster",
                                     renderer=_R(type="stretch")))
            else:
                ordered.append(Layer(name=op.output, source="", kind="vector"))
            declared.add(op.output)
    for l in ordered:
        if l.name in drawn or not l.visible:
            continue
        drawn.add(l.name)
        if l.kind == "raster":
            lines.extend(_emit_plot(l, spec, op_outputs))
            lines.append("    z += 1")
            continue
        if not l.source and l.name not in op_outputs:
            lines.append(f"    # (layer '{l.name}' has no source and no "
                         "producing operation — skipped)")
            continue
        lines.append(f"    if {l.name!r} in layers:")
        sub = _emit_plot(l, spec, op_outputs)
        lines.extend("    " + s if s.strip() else s for s in sub)
        lines.append("    z += 1")
    lines += [
        "",
        "    if CONFIG.get('basemap'):",
        "        add_basemap(ax, crs=(list(layers.values())[0].crs "
        "if layers else 'EPSG:3857'))",
        "    ax.set_title(CONFIG['title'], fontsize=14, fontweight='bold')",
        "    if CONFIG['subtitle']:",
        "        ax.text(0.5, 1.01, CONFIG['subtitle'], transform=ax.transAxes,",
        "                ha='center', fontsize=9, color='gray')",
        "    ax.text(0.99, 0.01, CONFIG['credits'], transform=ax.transAxes,",
        "            ha='right', fontsize=6, color='gray')",
        "    ax.set_axis_off()",
        "    if CONFIG['north_arrow']:",
        "        north_arrow(ax)",
        "    if CONFIG['scale_bar'] and layers:",
        "        scale_bar(ax, list(layers.values())[0])",
        "    out = CONFIG['export']",
        "    fig.savefig(out, dpi=CONFIG['dpi'], bbox_inches='tight')",
        "    log('exported -> ' + os.path.abspath(out))",
        "    if not os.path.exists(out):",
        "        raise SystemExit('export verification FAILED: ' + out)",
        "    log('ALL DONE')",
        "",
        "",
        "if __name__ == '__main__':",
        "    main()",
    ]
    return "\n".join(lines)
