"""
MapSpec -> standalone, executable ArcGIS Pro (arcpy) Python script.

Design rules:

* The generated script is SINGLE-FILE: the runtime helper block is inlined,
  so the user can drop one .py into ArcGIS Pro's Python window, a Pro
  notebook, or run it with propy.bat — no imports from this package.
* Everything data-specific lives in one CONFIG dict at the top of the
  script, so users can re-point paths without touching the logic.
* Every generated script is syntax-checked with ``ast.parse`` before it is
  returned; the generator refuses to hand over code that does not compile.
"""
from __future__ import annotations

import ast
import datetime
from typing import List

from ..spec import MapSpec, Layer, Operation, KNOWN_OPS
from .runtime import runtime_source

GENERATOR_NAME = "map2arcpy"


def generate(spec: MapSpec, strict: bool = True) -> str:
    """Compile a MapSpec into arcpy script text.

    strict=True raises ValueError on spec validation errors; strict=False
    embeds them as TODO comments and generates anyway.
    """
    errors = spec.validate()
    if errors and strict:
        raise ValueError("MapSpec invalid:\n  - " + "\n  - ".join(errors))

    parts: List[str] = []
    parts.append(_header(spec, errors))
    parts.append(_config_block(spec))
    parts.append("\n\n# %s\n# RUNTIME (inlined by %s — edit CONFIG, not this)\n# %s\n"
                 % ("=" * 74, GENERATOR_NAME, "=" * 74))
    parts.append(runtime_source())
    parts.append(_main_block(spec))
    code = "\n".join(parts)

    try:
        ast.parse(code)
    except SyntaxError as e:  # pragma: no cover - generator bug guard
        raise RuntimeError(f"internal error: generated script does not parse: {e}") from e
    return code


# --------------------------------------------------------------------------
# sections
# --------------------------------------------------------------------------
def _safe_text(s: str) -> str:
    """Neutralise text destined for docstrings/comments: input file content
    (layer names, titles) must never be able to escape into executable code."""
    s = " ".join(str(s).split())               # no newlines/control chars
    return s.replace('"""', "'''").replace("\\", "/")


def _header(spec: MapSpec, errors: List[str]) -> str:
    today = datetime.date.today().isoformat()
    title = _safe_text(spec.layout.title)
    lines = [
        "#!/usr/bin/env python",
        "# -*- coding: utf-8 -*-",
        '"""',
        f"{title}",
        f"{'-' * max(8, len(title))}",
        f"Generated by {GENERATOR_NAME} on {today} from a "
        f"'{spec.source_kind}' input.",
        "",
        "How to run (any one):",
        "  1. ArcGIS Pro -> Analysis -> Python window ->  exec(open(r'this_file.py').read())",
        "  2. ArcGIS Pro notebook:  %run this_file.py",
        '  3. Command line:  "C:/Program Files/ArcGIS/Pro/bin/Python/scripts/propy.bat" this_file.py',
        "     (option 3 needs CONFIG['aprx_template'] pointed at any blank .aprx)",
        "",
        "Edit the CONFIG block below — paths, EPSG, colours — then run.",
        '"""',
    ]
    for n in spec.notes:
        lines.append(f"# NOTE: {_safe_text(n)}")
    for e in errors:
        lines.append(f"# TODO (spec issue): {_safe_text(e)}")
    return "\n".join(lines)


def _config_block(spec: MapSpec) -> str:
    lay = spec.layout
    lines = ["", "", "# " + "=" * 74, "# CONFIG — everything you might need to change",
             "# " + "=" * 74, "CONFIG = {"]
    lines.append(f"    'epsg': {spec.crs_epsg!r},")
    lines.append(f"    'title': {lay.title!r},")
    lines.append(f"    'subtitle': {lay.subtitle!r},")
    credits = lay.credits or f"Generated with {GENERATOR_NAME} | CRS: EPSG:{spec.crs_epsg}"
    lines.append(f"    'credits': {credits!r},")
    lines.append(f"    'page': {lay.page!r},")
    lines.append(f"    'dpi': {lay.dpi!r},")
    lines.append(f"    'legend': {lay.legend!r}, 'north_arrow': {lay.north_arrow!r}, "
                 f"'scale_bar': {lay.scale_bar!r},")
    lines.append(f"    'export': {lay.export!r},")
    lines.append(f"    'extent': {spec.extent!r},  # WGS84 [xmin, ymin, xmax, ymax] or None")
    lines.append("    'aprx_template': None,  # set to a blank .aprx when running via propy.bat")
    op_outputs = {op.output for op in spec.operations if op.output}
    lines.append("    'sources': {")
    for l in spec.layers:
        if l.kind != "basemap" and not (l.name in op_outputs and not l.source):
            lines.append(f"        {l.name!r}: {l.source!r},")
    lines.append("    },")
    lines.append("}")
    return "\n".join(lines)


def _src(name_or_path: str, spec: MapSpec) -> str:
    """Emit an expression for an op input: CONFIG lookup for layers,
    results-gdb path for prior op outputs, literal otherwise."""
    layer_names = {l.name for l in spec.layers if l.kind != "basemap"}
    if name_or_path in layer_names:
        return f"CONFIG['sources'][{name_or_path!r}]"
    if name_or_path in {op.output for op in spec.operations if op.output}:
        return f"os.path.join(results, {name_or_path!r})"
    return repr(name_or_path)


def _emit_op(op: Operation, spec: MapSpec) -> List[str]:
    tool = KNOWN_OPS[op.tool]
    out = op.output or f"{op.tool}_out"
    out_expr = f"os.path.join(results, {out!r})"
    ins = [_src(i, spec) for i in op.inputs]
    p = op.params
    lines = [f"    # -- {op.tool} -> {out}"]
    if op.tool == "buffer":
        dist = p.get("distance", "500 Meters")
        lines.append(f"    {out} = {tool}({ins[0]}, {out_expr}, {dist!r},")
        lines.append(f"        dissolve_option={p.get('dissolve', 'NONE')!r})[0]")
    elif op.tool in ("clip", "erase"):
        lines.append(f"    {out} = {tool}({ins[0]}, {ins[1]}, {out_expr})[0]")
    elif op.tool == "dissolve":
        fld = p.get("field")
        lines.append(f"    {out} = {tool}({ins[0]}, {out_expr}, "
                     f"dissolve_field={([fld] if fld else None)!r})[0]")
    elif op.tool in ("intersect", "union", "merge"):
        lines.append(f"    {out} = {tool}([{', '.join(ins)}], {out_expr})[0]")
    elif op.tool == "spatial_join":
        rel = p.get("match_option", "INTERSECT")
        lines.append(f"    {out} = {tool}({ins[0]}, {ins[1]}, {out_expr},")
        lines.append(f"        match_option={rel!r})[0]")
    elif op.tool == "select":
        where = p.get("where", "1=1")
        lines.append(f"    {out} = {tool}({ins[0]}, {out_expr}, {where!r})[0]")
    elif op.tool == "near":
        lines.append(f"    {tool}({ins[0]}, {ins[1]})")
        lines.append(f"    {out} = {ins[0]}  # Near writes NEAR_FID/NEAR_DIST in place")
    elif op.tool == "project":
        epsg = p.get("epsg", spec.crs_epsg)
        lines.append(f"    {out} = {tool}({ins[0]}, {out_expr}, "
                     f"arcpy.SpatialReference({int(epsg)}))[0]")
    else:  # pragma: no cover — KNOWN_OPS is the gate
        lines.append(f"    # TODO: emit call for {tool}")
    lines.append(f"    log('{op.tool} done -> ' + str({out}))")
    return lines


def _emit_layer_add(l: Layer, spec: MapSpec) -> List[str]:
    lines = [f"    # -- layer: {l.name}"]
    if l.kind == "basemap":
        lines.append(f"    m.addBasemap({l.source!r})")
        return lines
    op_outputs = {op.output for op in spec.operations if op.output}
    if l.name in op_outputs and not l.source:
        lines.append(f"    lyr = m.addDataFromPath(os.path.join(results, {l.name!r}))")
    elif l.kind == "vector" and l.source.lower().endswith(".geojson"):
        geom = {"point": "POINT", "line": "POLYLINE"}.get(l.geometry or "", "POLYGON")
        lines.append(f"    _fc = geojson_to_fc(CONFIG['sources'][{l.name!r}],")
        lines.append(f"        os.path.join(results, {l.name!r}), {geom!r})")
        lines.append("    lyr = m.addDataFromPath(_fc)")
    else:
        lines.append(f"    lyr = m.addDataFromPath(CONFIG['sources'][{l.name!r}])")
    r = l.renderer
    if r.type == "unique" and r.field:
        lines.append(f"    apply_unique(lyr, {r.field!r}, {r.color_map!r})")
    elif r.type == "graduated" and r.field:
        lines.append(f"    apply_graduated(lyr, {r.field!r}, {r.breaks!r}, {r.ramp!r})")
    elif r.type == "stretch":
        lines.append(f"    apply_stretch(lyr, {r.ramp!r})")
    elif r.color:
        lines.append(f"    apply_simple(lyr, {r.color!r}, {r.outline!r}, {int(r.transparency)})")
    if l.definition_query:
        lines.append(f"    lyr.definitionQuery = {l.definition_query!r}")
    if l.label_field:
        lines.append("    try:")
        lines.append(f"        lc = lyr.listLabelClasses()[0]")
        lines.append(f"        lc.expression = '$feature.{l.label_field}'")
        lines.append("        lyr.showLabels = True")
        lines.append("    except Exception as e:")
        lines.append(f"        log('labels skipped: %s' % e, 'WARN')")
    if not l.visible:
        lines.append("    lyr.visible = False")
    for n in l.notes:
        lines.append(f"    # TODO: {_safe_text(n)}")
    return lines


def _main_block(spec: MapSpec) -> str:
    lines = ["", "", "# " + "=" * 74, "# MAIN", "# " + "=" * 74,
             "def _open_project():",
             "    try:",
             "        return arcpy.mp.ArcGISProject('CURRENT')",
             "    except Exception:",
             "        tpl = CONFIG.get('aprx_template')",
             "        if tpl and os.path.exists(tpl):",
             "            return arcpy.mp.ArcGISProject(tpl)",
             "        raise RuntimeError(",
             "            'Run inside ArcGIS Pro, or set CONFIG[\\'aprx_template\\'] '",
             "            'to any blank .aprx for command-line runs.')",
             "",
             "",
             "def main():",
             f"    banner(CONFIG['title'])",
             "    if not _HAS_ARCPY:",
             "        raise RuntimeError('arcpy not available — run inside ArcGIS Pro '",
             "                           '(see the docstring at the top of this file).')",
             "    check_pro_version()",
             "    work_dir = os.path.dirname(os.path.abspath(__file__)) or os.getcwd()",
             "    scratch, results = setup_env(work_dir, CONFIG['epsg'])",
             "    audit_exists(list(CONFIG['sources'].values()))",
             ""]

    if spec.operations:
        lines.append("    # ---- geoprocessing " + "-" * 40)
        for op in spec.operations:
            lines.extend(_emit_op(op, spec))
            lines.append("")

    lines.append("    # ---- map assembly " + "-" * 41)
    lines.append("    aprx = _open_project()")
    lines.append("    # build in a FRESH map — never mutate the user's existing maps")
    lines.append("    m = fresh_map(aprx, 'map2arcpy - ' + CONFIG['title'])")
    lines.append("")

    # basemaps first (bottom of the drawing order), then data layers
    ordered = [l for l in spec.layers if l.kind == "basemap"] + \
              [l for l in spec.layers if l.kind != "basemap"]
    # layers produced by operations but not declared explicitly:
    declared = {l.name for l in spec.layers}
    for op in spec.operations:
        if op.output and op.output not in declared:
            ordered.append(Layer(name=op.output, source="", kind="vector"))
            declared.add(op.output)
    for l in ordered:
        lines.extend(_emit_layer_add(l, spec))
        lines.append("")

    lines.extend([
        "    # ---- layout + export " + "-" * 38,
        "    layout = build_layout(aprx, m, CONFIG)",
        "    if CONFIG.get('extent'):",
        "        set_extent(layout, CONFIG['extent'])",
        "    out_path = CONFIG['export']",
        "    if not os.path.isabs(out_path):",
        "        out_path = os.path.join(work_dir, out_path)",
        "    export_layout(layout, out_path, CONFIG['dpi'])",
        "    log('ALL DONE')",
        "",
        "",
        "if __name__ == '__main__':",
        "    main()",
        "",
    ])
    return "\n".join(lines)
