"""
MapSpec -> standalone, executable ArcGIS Pro (arcpy) Python script.

Design rules:

* The generated script is SINGLE-FILE: the runtime helper block is inlined,
  so the user can drop one .py into ArcGIS Pro's Python window, a Pro
  notebook, or run it with propy.bat — no imports from this package.
* Everything data-specific lives in one CONFIG dict at the top of the
  script, so users can re-point paths without touching the logic.
* Every generated script is syntax-checked with ``ast.parse`` before it is
  returned; the generator refuses to hand over code that does not compile.
"""
from __future__ import annotations

import ast
import datetime
import os
from typing import Any, Dict, List, Optional

from ..spec import MapSpec, Layer, Operation, KNOWN_OPS, CLASSIC_OPS
from ..probe import use_classic_tools, pro_version
from .runtime import runtime_source

GENERATOR_NAME = "map2arcpy"


def generate(spec: MapSpec, strict: bool = True,
             profile: Optional[Dict[str, Any]] = None) -> str:
    """Compile a MapSpec into arcpy script text.

    strict=True raises ValueError on spec validation errors; strict=False
    embeds them as TODO comments and generates anyway.

    profile: a saved ArcGIS Pro environment profile (see map2arcpy probe) —
    when given, generation adapts: classic tools on old Pro, basemaps
    commented out without a portal sign-in, aprx_template pre-filled.
    """
    errors = spec.validate()
    if errors and strict:
        raise ValueError("MapSpec invalid:\n  - " + "\n  - ".join(errors))

    ops_map = CLASSIC_OPS if use_classic_tools(profile) else KNOWN_OPS
    parts: List[str] = []
    parts.append(_header(spec, errors, profile))
    parts.append(_config_block(spec, profile))
    parts.append("\n\n# %s\n# RUNTIME (inlined by %s — edit CONFIG, not this)\n# %s\n"
                 % ("=" * 74, GENERATOR_NAME, "=" * 74))
    parts.append(runtime_source())
    parts.append(_main_block(spec, ops_map, profile))
    code = "\n".join(parts)

    try:
        ast.parse(code)
    except SyntaxError as e:  # pragma: no cover - generator bug guard
        raise RuntimeError(f"internal error: generated script does not parse: {e}") from e
    return code


# --------------------------------------------------------------------------
# sections
# --------------------------------------------------------------------------
def _safe_text(s: str) -> str:
    """Neutralise text destined for docstrings/comments: input file content
    (layer names, titles) must never be able to escape into executable code."""
    s = " ".join(str(s).split())               # no newlines/control chars
    return s.replace('"""', "'''").replace("\\", "/")


def _header(spec: MapSpec, errors: List[str],
            profile: Optional[Dict[str, Any]] = None) -> str:
    today = datetime.date.today().isoformat()
    title = _safe_text(spec.layout.title)
    lines = [
        "#!/usr/bin/env python",
        "# -*- coding: utf-8 -*-",
        '"""',
        f"{title}",
        f"{'-' * max(8, len(title))}",
        f"Generated by {GENERATOR_NAME} on {today} from a "
        f"'{spec.source_kind}' input.",
        "",
        "How to run (any one):",
        "  1. ArcGIS Pro -> Analysis -> Python window ->  exec(open(r'this_file.py').read())",
        "  2. ArcGIS Pro notebook:  %run this_file.py",
        '  3. Command line:  "C:/Program Files/ArcGIS/Pro/bin/Python/scripts/propy.bat" this_file.py',
        "     (option 3 needs CONFIG['aprx_template'] pointed at any blank .aprx)",
        "",
        "Edit the CONFIG block below — paths, EPSG, colours — then run.",
        '"""',
    ]
    if profile:
        v = profile.get("pro_version")
        portal = "portal signed in" if profile.get("portal_signed_in") else "NO portal sign-in"
        lines.append(f"# Matched to your machine (map2arcpy probe): ArcGIS Pro {v}, "
                     f"{_safe_text(profile.get('license') or '?')} license, {portal}")
        pv = pro_version(profile)
        if pv and pv[0] < 3:
            lines.append(f"# TODO (Pro version): your profile reports Pro {v} — the "
                         "layout section (createLayout) needs Pro 3.x; the map and "
                         "geoprocessing parts will still run")
    else:
        lines.append("# TIP: run `map2arcpy probe` once in ArcGIS Pro so scripts are "
                     "matched to your Pro version, licenses and portal")
    for n in spec.notes:
        lines.append(f"# NOTE: {_safe_text(n)}")
    for e in errors:
        lines.append(f"# TODO (spec issue): {_safe_text(e)}")
    return "\n".join(lines)


def _config_block(spec: MapSpec, profile: Optional[Dict[str, Any]] = None) -> str:
    lay = spec.layout
    lines = ["", "", "# " + "=" * 74, "# CONFIG — everything you might need to change",
             "# " + "=" * 74, "CONFIG = {"]
    lines.append(f"    'epsg': {spec.crs_epsg!r},")
    lines.append(f"    'title': {lay.title!r},")
    lines.append(f"    'subtitle': {lay.subtitle!r},")
    credits = lay.credits or f"Generated with {GENERATOR_NAME} | CRS: EPSG:{spec.crs_epsg}"
    lines.append(f"    'credits': {credits!r},")
    lines.append(f"    'page': {lay.page!r},")
    lines.append(f"    'dpi': {lay.dpi!r},")
    lines.append(f"    'legend': {lay.legend!r}, 'north_arrow': {lay.north_arrow!r}, "
                 f"'scale_bar': {lay.scale_bar!r},")
    lines.append(f"    'export': {lay.export!r},")
    lines.append(f"    'extent': {spec.extent!r},  # WGS84 [xmin, ymin, xmax, ymax] or None")
    tpl = ((profile or {}).get("project") or {}).get("path")
    if tpl:
        lines.append(f"    'aprx_template': {tpl!r},  # your project, from the Pro profile "
                     "(used for propy.bat runs)")
    else:
        lines.append("    'aprx_template': None,  # set to a blank .aprx when running via propy.bat")
    op_outputs = {op.output for op in spec.operations if op.output}
    lines.append("    'sources': {")
    for l in spec.layers:
        if l.kind != "basemap" and not (l.name in op_outputs and not l.source):
            lines.append(f"        {l.name!r}: {l.source!r},")
    lines.append("    },")
    lines.append("}")
    return "\n".join(lines)


def _src(name_or_path: str, spec: MapSpec) -> str:
    """Emit an expression for an op input: CONFIG lookup for layers,
    results-gdb path for prior op outputs, literal otherwise."""
    layer_names = {l.name for l in spec.layers if l.kind != "basemap"}
    if name_or_path in layer_names:
        return f"CONFIG['sources'][{name_or_path!r}]"
    if name_or_path in {op.output for op in spec.operations if op.output}:
        return f"os.path.join(results, {name_or_path!r})"
    return repr(name_or_path)


def _emit_op(op: Operation, spec: MapSpec, ops_map: Dict[str, str]) -> List[str]:
    tool = ops_map[op.tool]
    out = op.output or f"{op.tool}_out"
    out_expr = f"os.path.join(results, {out!r})"
    ins = [_src(i, spec) for i in op.inputs]
    p = op.params
    lines = [f"    # -- {op.tool} -> {out}"]
    if op.tool == "buffer":
        dist = p.get("distance", "500 Meters")
        lines.append(f"    {out} = {tool}({ins[0]}, {out_expr}, {dist!r},")
        lines.append(f"        dissolve_option={p.get('dissolve', 'NONE')!r})[0]")
    elif op.tool in ("clip", "erase"):
        lines.append(f"    {out} = {tool}({ins[0]}, {ins[1]}, {out_expr})[0]")
    elif op.tool == "dissolve":
        fld = p.get("field")
        lines.append(f"    {out} = {tool}({ins[0]}, {out_expr}, "
                     f"dissolve_field={([fld] if fld else None)!r})[0]")
    elif op.tool in ("intersect", "union", "merge"):
        lines.append(f"    {out} = {tool}([{', '.join(ins)}], {out_expr})[0]")
    elif op.tool == "spatial_join":
        rel = p.get("match_option", "INTERSECT")
        lines.append(f"    {out} = {tool}({ins[0]}, {ins[1]}, {out_expr},")
        lines.append(f"        match_option={rel!r})[0]")
    elif op.tool == "select":
        where = p.get("where", "1=1")
        lines.append(f"    {out} = {tool}({ins[0]}, {out_expr}, {where!r})[0]")
    elif op.tool == "near":
        lines.append(f"    {tool}({ins[0]}, {ins[1]})")
        lines.append(f"    {out} = {ins[0]}  # Near writes NEAR_FID/NEAR_DIST in place")
    elif op.tool == "project":
        epsg = p.get("epsg", spec.crs_epsg)
        lines.append(f"    {out} = {tool}({ins[0]}, {out_expr}, "
                     f"arcpy.SpatialReference({int(epsg)}))[0]")
    else:  # pragma: no cover — KNOWN_OPS is the gate
        lines.append(f"    # TODO: emit call for {tool}")
    lines.append(f"    log('{op.tool} done -> ' + str({out}))")
    return lines


def _emit_layer_add(l: Layer, spec: MapSpec, basemap_ok: bool = True) -> List[str]:
    lines = [f"    # -- layer: {l.name}"]
    if l.kind == "basemap":
        if basemap_ok:
            lines.append(f"    m.addBasemap({l.source!r})")
        else:
            lines.append(f"    # m.addBasemap({l.source!r})  # commented out: your Pro "
                         "profile reports no portal sign-in, so this basemap would fail; "
                         "sign in and uncomment, or re-run `map2arcpy probe`")
        return lines
    op_outputs = {op.output for op in spec.operations if op.output}
    ext = os.path.splitext(l.source.lower())[1] if l.source else ""
    src = f"CONFIG['sources'][{l.name!r}]"
    guarded = False                                # helper loaders may return None
    if l.name in op_outputs and not l.source:
        lines.append(f"    lyr = m.addDataFromPath(os.path.join(results, {l.name!r}))")
    elif l.kind == "vector" and ext == ".geojson":
        geom = {"point": "POINT", "line": "POLYLINE"}.get(l.geometry or "", "POLYGON")
        lines.append(f"    _fc = geojson_to_fc({src},")
        lines.append(f"        os.path.join(results, {l.name!r}), {geom!r})")
        lines.append("    lyr = m.addDataFromPath(_fc)")
    elif ext == ".nc":
        x = l.extra.get("variable", "TODO_VARIABLE")
        lines.append(f"    lyr = add_netcdf(m, results, {src}, {l.name!r},")
        lines.append(f"        {x!r}, {l.extra.get('x_dim', 'lon')!r}, "
                     f"{l.extra.get('y_dim', 'lat')!r})")
        guarded = True
    elif ext == ".gpx":
        lines.append(f"    lyr = add_gpx(m, results, {src}, {l.name!r})")
        guarded = True
    elif ext == ".csv":
        xf = l.extra.get("x_field", "TODO_X_FIELD")
        yf = l.extra.get("y_field", "TODO_Y_FIELD")
        lines.append(f"    lyr = add_csv_xy(m, results, {src}, {l.name!r},")
        lines.append(f"        {xf!r}, {yf!r}, CONFIG['epsg'] if {xf!r} not in "
                     f"('lat', 'lon', 'latitude', 'longitude', 'lng', 'long') else 4326)")
        guarded = True
    elif ext in (".kml", ".kmz"):
        lines.append(f"    lyr = add_kml(m, work_dir, {src}, {l.name!r})")
        guarded = True
    else:
        lines.append(f"    lyr = m.addDataFromPath({src})")

    body: List[str] = []
    r = l.renderer
    if r.type == "unique" and r.field:
        body.append(f"apply_unique(lyr, {r.field!r}, {r.color_map!r})")
    elif r.type == "graduated" and r.field:
        body.append(f"apply_graduated(lyr, {r.field!r}, {r.breaks!r}, {r.ramp!r})")
    elif r.type == "stretch":
        body.append(f"apply_stretch(lyr, {r.ramp!r})")
    elif r.color:
        body.append(f"apply_simple(lyr, {r.color!r}, {r.outline!r}, {int(r.transparency)})")
    if l.definition_query:
        body.append(f"lyr.definitionQuery = {l.definition_query!r}")
    if l.label_field:
        body.append("try:")
        body.append(f"    lc = lyr.listLabelClasses()[0]")
        body.append(f"    lc.expression = '$feature.{l.label_field}'")
        body.append("    lyr.showLabels = True")
        body.append("except Exception as e:")
        body.append(f"    log('labels skipped: %s' % e, 'WARN')")
    if not l.visible:
        body.append("lyr.visible = False")
    if guarded and body:
        lines.append("    if lyr:")
        lines.extend("        " + b for b in body)
    else:
        lines.extend("    " + b for b in body)
    for n in l.notes:
        lines.append(f"    # TODO: {_safe_text(n)}")
    return lines


def _main_block(spec: MapSpec, ops_map: Dict[str, str],
                profile: Optional[Dict[str, Any]] = None) -> str:
    basemap_ok = profile is None or bool(profile.get("portal_signed_in"))
    lines = ["", "", "# " + "=" * 74, "# MAIN", "# " + "=" * 74,
             "def _open_project():",
             "    try:",
             "        return arcpy.mp.ArcGISProject('CURRENT')",
             "    except Exception:",
             "        tpl = CONFIG.get('aprx_template')",
             "        if tpl and os.path.exists(tpl):",
             "            return arcpy.mp.ArcGISProject(tpl)",
             "        raise RuntimeError(",
             "            'Run inside ArcGIS Pro, or set CONFIG[\\'aprx_template\\'] '",
             "            'to any blank .aprx for command-line runs.')",
             "",
             "",
             "def main():",
             f"    banner(CONFIG['title'])",
             "    if not _HAS_ARCPY:",
             "        raise RuntimeError('arcpy not available — run inside ArcGIS Pro '",
             "                           '(see the docstring at the top of this file).')",
             "    check_pro_version()",
             "    work_dir = os.path.dirname(os.path.abspath(__file__)) or os.getcwd()",
             "    scratch, results = setup_env(work_dir, CONFIG['epsg'])",
             "    audit_exists(list(CONFIG['sources'].values()))",
             ""]

    if spec.operations:
        lines.append("    # ---- geoprocessing " + "-" * 40)
        for op in spec.operations:
            lines.extend(_emit_op(op, spec, ops_map))
            lines.append("")

    lines.append("    # ---- map assembly " + "-" * 41)
    lines.append("    aprx = _open_project()")
    lines.append("    # build in a FRESH map — never mutate the user's existing maps")
    lines.append("    m = fresh_map(aprx, 'map2arcpy - ' + CONFIG['title'])")
    lines.append("")

    # basemaps first (bottom of the drawing order), then data layers
    ordered = [l for l in spec.layers if l.kind == "basemap"] + \
              [l for l in spec.layers if l.kind != "basemap"]
    # layers produced by operations but not declared explicitly:
    declared = {l.name for l in spec.layers}
    for op in spec.operations:
        if op.output and op.output not in declared:
            ordered.append(Layer(name=op.output, source="", kind="vector"))
            declared.add(op.output)
    for l in ordered:
        lines.extend(_emit_layer_add(l, spec, basemap_ok))
        lines.append("")

    lines.extend([
        "    # ---- layout + export " + "-" * 38,
        "    layout = build_layout(aprx, m, CONFIG)",
        "    if CONFIG.get('extent'):",
        "        set_extent(layout, CONFIG['extent'])",
        "    out_path = CONFIG['export']",
        "    if not os.path.isabs(out_path):",
        "        out_path = os.path.join(work_dir, out_path)",
        "    export_layout(layout, out_path, CONFIG['dpi'])",
        "    log('ALL DONE')",
        "",
        "",
        "if __name__ == '__main__':",
        "    main()",
        "",
    ])
    return "\n".join(lines)
